services:

  index:
    build: .
    container_name: ${INDEX_CONTAINER_NAME:-index}    
    hostname: ${INDEX_HOSTNAME:-index}    
    image: ${INDEX_IMAGE:-index}:${INDEX_VERSION:-latest}
    ports:
      - 8000:80
    restart: unless-stopped
    volumes:
      - ${INDEX_VOLUME_ETC_INDEX:-./mnt/etc/index}:/etc/index
      - ${INDEX_VOLUME_ETC_INDEX_ICONS:-./mnt/var/lib/index/icons}:/opt/index/icons/custom
