services:

  index:
    build: .
    container_name: services-index
    hostname: ${INDEX_HOSTNAME:-services-index}    
    image: services/index:${INDEX_VERSION:-latest}
    ports:
      - 8000:80
    restart: unless-stopped
    volumes:
      - ${INDEX_VOLUME_ETC:-./volumes/etc/index}:/etc/index
      - ${INDEX_VOLUME_SRC:-./src}:/opt/index
      - ${INDEX_VOLUME_SRC_ICONS:-./volumes/opt/index/public/images/icons/custom}:/opt/index/public/images/icons/custom
